ProjectList: update to match current semester teams' repository
nus-cs2103-AY1718S2/website pull request #7
Opened 2018-03-14 00:54 UTC by eugenepeh

2018-03-14 00:55 UTC, eugenepeh commented
@sooyj @okkhoy @hwkchia, for your review.

2018-03-15 05:28 UTC, okkhoy requested changes
Hi Eugene,
Thanks for this! Since you have the groundwork done, can you update the PR with the necessary changes indicated?

Thanks,
Akshay

2018-03-15 05:28 UTC, okkhoy commented on admin/projectList.md
> +### [B1](http://github.com/CS2103JAN2018-T10-B1/main)
There is no T10 this time. Please remove them

2018-03-15 05:28 UTC, okkhoy commented on admin/projectList.md
> +### [B1](http://github.com/CS2103JAN2018-T12-B1/main)
There is no T12

2018-03-15 05:28 UTC, okkhoy commented on admin/projectList.md
> +### [B2](http://github.com/CS2103JAN2018-T13-B2/main)
There is no T13

2018-03-15 05:28 UTC, okkhoy commented on admin/projectList.md
> +### [B4](http://github.com/CS2103JAN2018-T14-B4/main)
There is no T14

2018-03-15 05:28 UTC, okkhoy commented on admin/projectList.md
> +### [B1](http://github.com/CS2103JAN2018-T17-B1/main)
There is no T17

2018-03-15 05:28 UTC, okkhoy commented on admin/projectList.md
> +### [B1](http://github.com/CS2103JAN2018-F10-B1/main)
There is no F10

2018-03-15 05:28 UTC, okkhoy commented on admin/projectList.md
> +<img src="https://rawgit.com/CS2103JAN2018-F11-B4/main/master/docs/images/Ui.png" width="600"/>
Please add F12 and F14

2018-03-15 07:11 UTC, eugenepeh commented
@okkhoy made changes as requested. Thanks for the heads up, forgot that tutorial slots changes.

2018-03-16 01:20 UTC, okkhoy approved these changes

2018-03-16 01:23 UTC, merged